version: '3'
services:
  postgis:
    image: mdillon/postgis
    ports:
        - "5432:5432"
    environment:
        - "POSTGRES_PASSWORD=test"
    restart: always
    volumes:
        - "../pg_data:/var/lib/postgresql/data"
  geoserver:
    image: oscarfonts/geoserver
    depends_on:
        - postgis
    ports:
        - "8080:8080"
    links:
        - "postgis:postgis"
    restart: always